# Generated by Django 4.2 on 2023-07-06 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('first_register', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='code_element_module')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='code_filiere')),
                ('nom', models.CharField(max_length=255, verbose_name='nom_filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255, verbose_name='code_module')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=255, unique=True, verbose_name='annee promo')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='num_sem')),
                ('annee', models.CharField(max_length=255, verbose_name='annee promo')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abs.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('heure', models.CharField(max_length=255)),
                ('e_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abs.emodule')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abs.filiere')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abs.module')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abs.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prenom')),
                ('Tel', models.CharField(max_length=8, unique=True, verbose_name='Tel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'professeur',
                'verbose_name_plural': 'professeurs',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='ResponsabeModule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abs.professeur'),
        ),
        migrations.AddField(
            model_name='module',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abs.semestre'),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prenom')),
                ('CIN', models.CharField(max_length=8, unique=True, verbose_name='CIN')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abs.filiere')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'etudiant',
                'verbose_name_plural': 'etudiants',
            },
        ),
        migrations.AddField(
            model_name='emodule',
            name='ResponsabeModule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abs.professeur'),
        ),
        migrations.AddField(
            model_name='emodule',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abs.filiere'),
        ),
        migrations.AddField(
            model_name='emodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abs.module'),
        ),
        migrations.AddField(
            model_name='emodule',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abs.semestre'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prenom')),
                ('Tel', models.CharField(max_length=8, unique=True, verbose_name='Tel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence', models.BooleanField()),
                ('commentaire', models.CharField(max_length=255, verbose_name='commentaire')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abs.etudiant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abs.seance')),
            ],
        ),
    ]
