# Generated by Django 4.2 on 2023-07-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_abs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='e_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_abs.emodule'),
        ),
    ]
